version: "3.9"
# ref: https://docs.docker.com/compose/compose-file
services:
  app:
    image: go-modular-monolith
    build:
      args:
        - target=dev
    environment:
      APP_ENV: dev
      PORT: 8080
      APP_DB_HOST: db
      APP_DB_PORT: 3306
      APP_DB_USER: db_user
      APP_DB_PASSWORD: db_password
      APP_DB_NAME: go_modular_monolith
      APP_REDIS_HOST: redis
      APP_REDIS_PORT: 6379
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "18000:8080"
    links:
      - db:db
      - redis:redis
    networks:
      - app-networks
  db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: go_modular_monolith
    volumes:
      - db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
    networks:
      - app-networks
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      PMA_USER: db_user
      PMA_PASSWORD: db_password
      PMA_HOST: db
    networks:
      - app-networks
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "36379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-networks
volumes:
  db-data:
  redis-data:
networks:
  app-networks:
    driver: bridge
